version: '3.8'

services:
  db:
    image: mysql:8.0
    container_name: monitor_db
    restart: always
    environment:
      MYSQL_ROOT_PASSWORD: "9f8c7b6A5!2d#4"
      MYSQL_DATABASE: dashboard_db
      MYSQL_USER: db_admin
      MYSQL_PASSWORD: "3kL9@pT2z!wQx"
    ports:
      - "3308:3306"
    volumes:
      - ./db-data:/var/lib/mysql

  phpmyadmin:
    image: phpmyadmin/phpmyadmin
    container_name: monitor_phpmyadmin
    restart: always
    environment:
      PMA_HOST: db
      MYSQL_ROOT_PASSWORD: "9f8c7b6A5!2d#4"
    ports:
      - "8081:80"
    depends_on:
      - db

  # backend-api:
  #   build: ./backend
  #   container_name: monitor_backend
  #   ports:
  #     - "8080:8080"
  #   depends_on:
  #     - db

  # frontend-web:
  #   build: ./frontend
  #   container_name: monitor_frontend
  #   ports:
  #     - "3000:80"
